using Llm.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using YamlDotNet.Serialization;

namespace Llm.Api.Identity;

/// <summary>
/// Writes the hash-free list of people Argus reads (email -> username), in the
/// format the admin panel wrote. Replaced atomically, so a reader never sees half a file.
/// </summary>
public sealed class DirectoryFile(AppDbContext db, IOptions<AuthOptions> options, ILogger<DirectoryFile> logger)
{
    public async Task WriteAsync(CancellationToken ct = default)
    {
        var path = options.Value.DirectoryFile;
        if (string.IsNullOrEmpty(path))
        {
            return;
        }
        var people = await db.Users.AsNoTracking().Where(u => !u.IsDisabled).OrderBy(u => u.UserName)
            .Select(u => new { u.UserName, u.DisplayName, u.Email }).ToListAsync(ct);
        var doc = new Dictionary<string, object>
        {
            ["users"] = people.ToDictionary(p => p.UserName!, p => new Dictionary<string, string>
            {
                ["displayname"] = p.DisplayName,
                ["email"] = p.Email ?? "",
            }),
        };
        var yaml = "# GENERATED by the app from its people. No passwords.\n" + new SerializerBuilder().Build().Serialize(doc);
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            var tmp = path + ".tmp";
            await File.WriteAllTextAsync(tmp, yaml, ct);
            File.Move(tmp, path, overwrite: true);
        }
        catch (IOException ex)
        {
            LogWriteFailed(logger, path, ex);
        }
        catch (UnauthorizedAccessException ex)
        {
            LogWriteFailed(logger, path, ex);
        }
    }

    private static readonly Action<ILogger, string, Exception?> LogWriteFailed =
        LoggerMessage.Define<string>(LogLevel.Warning, new EventId(1, "DirectoryWriteFailed"), "Could not write the people directory {Path}");
}
