#!/usr/bin/env python3
"""Regenerate dotnet/src/Argus/Server/ToolCatalog.g.cs from the Python server.

    python dotnet/scripts/gen-tool-catalog.py            # rewrite the file
    python dotnet/scripts/gen-tool-catalog.py --check    # exit 1 if it is stale

Tool names, descriptions and JSON schemas are part of what a model sees, so
the .NET server serves exactly the Python server's `tools/list`: this builds
the Python app in-process against a throwaway database with no packs
installed (so docs_find carries its base description; both implementations
append the installed pack names at startup), and writes every tool in the
order FastMCP lists them. Run it with an interpreter that has the argus
package installed, after changing a tool's signature or docstring in Python.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "dotnet" / "src" / "Argus" / "Server" / "ToolCatalog.g.cs"

HEADER = """\
// <auto-generated>
// Generated from the Python server's tools/list response (argus/mcpsrv/tools.py),
// so names, descriptions and schemas are byte-identical across implementations.
// Regenerate with dotnet/scripts/gen-tool-catalog.py after changing a tool in Python.
// </auto-generated>
namespace Argus.Server;

public static partial class ToolCatalog
{
"""


def cs_string(text: str) -> str:
    """A C# regular string literal. Line and paragraph separators are escaped
    too: C# treats them as newlines, so left raw they end the literal."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ch in "\x7f\x85  ":
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def schema(value) -> str:
    # Insertion order, as pydantic produced it and FastMCP serves it.
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


async def list_tools():
    from argus.config import Config
    from argus.mcpsrv.server import SERVER_INSTRUCTIONS, create_app

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "packs").mkdir()
        cfg_path = root / "config.yaml"
        cfg_path.write_text(
            "gitlab:\n  url: http://127.0.0.1:1\n  token: unused\n"
            f"index:\n  data_dir: {root / 'data'}\n  db_path: {root / 'data' / 'index.db'}\n"
            f"packs:\n  dir: {root / 'packs'}\n",
            encoding="utf-8")
        (root / "data").mkdir()
        server = create_app(Config.load(cfg_path))
        tools = await server.list_tools()
    return SERVER_INSTRUCTIONS, tools


def render(instructions: str, tools) -> str:
    lines = [HEADER.rstrip("\n"),
             f"    public const string ServerInstructions = {cs_string(instructions)};",
             "",
             "    public static readonly ToolSpec[] Specs =",
             "    ["]
    for tool in tools:
        if tool.outputSchema is None:
            raise SystemExit(f"{tool.name}: no output schema; ToolSpec needs one")
        lines += [f"        new({cs_string(tool.name)},",
                  f"            {cs_string(tool.description or '')},",
                  f"            {cs_string(schema(tool.inputSchema))},",
                  f"            {cs_string(schema(tool.outputSchema))}),"]
    lines += ["    ];", "}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="Compare instead of writing; exit 1 when the file is stale")
    args = parser.parse_args()
    sys.path.insert(0, str(REPO / "src"))
    text = render(*asyncio.run(list_tools()))
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if args.check:
        if current != text:
            print(f"{OUT.relative_to(REPO)} is stale; run {Path(__file__).relative_to(REPO)}", file=sys.stderr)
            return 1
        print("tool catalog is current")
        return 0
    if current == text:
        print("tool catalog already current")
    else:
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
