using System.Text.Json;
using System.Text.RegularExpressions;
using Argus.Util;

namespace Argus.Indexing;

/// <summary>
/// What a file declares about the estate: what it provides (a package by its name, a module, a namespace, a .proto
/// file) and what it uses (a package reference, an import, a submodule, a CI include, an image). Read from the text the
/// index already stores, by the conventions of each ecosystem; no build is run. Resolving uses against provides links
/// repositories (Graph.RebuildLinks).
/// </summary>
public static partial class Links
{
    public const string Provides = "provides";
    public const string Uses = "uses";

    /// <summary>
    /// One declaration: provides or uses, its kind (nuget, npm, pypi, go, maven, cargo, cs, cs-type, java, java-package,
    /// py, py-file, proto, repo, image, ts-alias), the name, its line; its form (how it was declared: a submodule, a CI
    /// include, a Dockerfile's base image, a deployment's image), its scope (main, or test: a test's code, a dev or test
    /// dependency) and its origin (source, manifest, generated code, a sample or fixture).
    /// </summary>
    public readonly record struct Decl(string Role, string Kind, string Name, long Line, string Form = "", string Scope = "main", string Origin = "source");

    /// <summary>A test's file: under a tests folder, or named as tests are (x_test.go, test_x.py, x.test.ts, XTests.cs, XTest.java).</summary>
    public static bool IsTestPath(string path)
    {
        var parts = path.Split('/');
        foreach (var part in parts[..^1])
        {
            var p = part.ToLowerInvariant();
            if (p is "test" or "tests" or "__tests__" or "spec" or "specs" or "testing" or "e2e" || p.EndsWith(".tests", StringComparison.Ordinal)
                || p.EndsWith(".test", StringComparison.Ordinal) || p.EndsWith(".unittests", StringComparison.Ordinal) || p.EndsWith(".integrationtests", StringComparison.Ordinal))
                return true;
        }
        var name = parts[^1];
        return name.EndsWith("_test.go", StringComparison.Ordinal) || name.StartsWith("test_", StringComparison.Ordinal) && name.EndsWith(".py", StringComparison.Ordinal)
            || name.EndsWith("_test.py", StringComparison.Ordinal) || TestFileName().IsMatch(name);
    }

    /// <summary>A sample's, a fixture's, a template's or a benchmark's file: what it declares is nobody's library.</summary>
    public static bool IsSamplePath(string path)
    {
        foreach (var part in path.Split('/')[..^1])
        {
            if (part.ToLowerInvariant() is "examples" or "example" or "samples" or "sample" or "demo" or "demos" or "templates" or "fixtures"
                or "testdata" or "test-data" or "benchmarks" or "playground" or "sandbox")
                return true;
        }
        return false;
    }

    /// <summary>Code a tool wrote (it says so at its top): what it declares is its source's (a .proto, an OpenAPI document).</summary>
    public static bool IsGenerated(string content)
    {
        var top = content.Length > 2000 ? content[..2000] : content;
        return top.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) || top.Contains("Code generated by", StringComparison.Ordinal)
            || top.Contains("DO NOT EDIT", StringComparison.Ordinal) || top.Contains("@generated", StringComparison.Ordinal)
            || top.Contains("Generated by the protocol buffer compiler", StringComparison.Ordinal);
    }

    [GeneratedRegex(@"(?:\.(?:test|spec)\.[cm]?[jt]sx?|Tests?\.(?:cs|java|kt)|Spec\.(?:java|kt|groovy))$")]
    private static partial Regex TestFileName();

    /// <summary>The languages that are manifests, not code: their declarations are read, no symbols.</summary>
    public static readonly HashSet<string> ManifestLangs = new(StringComparer.Ordinal)
    {
        "msbuild", "npm", "gomod", "maven", "gradle", "cargo", "toml", "yaml", "gitmodules", "dockerfile", "ini", "nugetconfig", "tsconfig",
    };

    public static List<Decl> Extract(string path, string? lang, string content)
    {
        var output = new List<Decl>();
        var name = path[(path.LastIndexOf('/') + 1)..];
        try
        {
            switch (lang)
            {
                case "msbuild": MsBuild(name, content, output); break;
                case "nugetconfig": Matches(PackagesConfig(), content, "nuget", output, lower: true); break;
                case "npm": PackageJson(content, output); break;
                case "tsconfig": TsConfig(content, output); break;
                case "gomod": GoMod(content, output); break;
                case "maven": Pom(content, output); break;
                case "gradle":
                    Matches(GradleDep(), content, "maven", output, lower: true, join: m => $"{m.Groups["g"].Value}:{m.Groups["a"].Value}",
                        scope: m => m.Groups["conf"].Value.StartsWith("test", StringComparison.Ordinal) ? "test" : "main");
                    Matches(GradleMapDep(), content, "maven", output, lower: true, join: m => $"{m.Groups["g"].Value}:{m.Groups["a"].Value}",
                        scope: m => m.Groups["conf"].Value.StartsWith("test", StringComparison.Ordinal) ? "test" : "main");
                    break;
                case "toml" when name == "libs.versions.toml": GradleCatalog(content, output); break;
                case "cargo": Cargo(content, output); break;
                case "toml" when name == "pyproject.toml": PyProject(content, output); break;
                case "ini" when name == "setup.cfg": SetupCfg(content, output); break;
                case "text" when IsRequirements(path, name): Requirements(content, output); break;
                case "gitmodules":
                    // A relative URL (../core/protos.git) is the estate's own, from this repository's path (Graph resolves it).
                    Matches(SubmoduleUrl(), content, "repo", output, lower: true, form: "submodule",
                        join: m => m.Groups["url"].Value.StartsWith("../", StringComparison.Ordinal) || m.Groups["url"].Value.StartsWith("./", StringComparison.Ordinal)
                            ? "rel:" + m.Groups["url"].Value.Trim('"', '\'').Replace(".git", "", StringComparison.Ordinal).TrimEnd('/')
                            : RepoPathOf(m.Groups["url"].Value));
                    break;
                // CI's own files: .gitlab-ci.yml, and what it includes from .gitlab/ (.gitlab/ci/build.yml).
                case "yaml": Yaml(name, content, output, isCi: path.StartsWith(".gitlab/", StringComparison.Ordinal) || path.Contains("/.gitlab/", StringComparison.Ordinal)); break;
                case "dockerfile": Matches(DockerFrom(), content, "image", output, lower: true, join: m => ImagePath(m.Groups["image"].Value), form: "base"); break;
                case "csharp": CSharp(CodeText.Blank("csharp", content), output); break;
                case "python": Python(path, CodeText.Blank("python", content), output); break;
                case "typescript" or "javascript": JavaScript(content, output); break;
                case "go": Go(CodeText.Blank("go", content, keepStrings: true), output); break;
                case "java" or "kotlin": Java(CodeText.Blank(lang, content), output); break;
                case "rust": Matches(RustUse(), content, "cargo", output, lower: true, join: m => m.Groups["crate"].Value.Replace('_', '-')); break;
                case "proto": Proto(path, content, output); break;
            }
        }
        catch (Exception e) when (e is JsonException or RegexMatchTimeoutException or ArgumentException)
        {
            // A file this cannot read declares nothing: the rest of the estate is still linked.
        }
        // A test's file, a test project's manifest: its uses are the tests'; a sample's or generated file provides for nobody.
        var stem = name.Contains('.') ? name[..name.LastIndexOf('.')] : name;
        var last = stem[(stem.LastIndexOf('.') + 1)..];
        var test = IsTestPath(path) || (lang == "msbuild" && (last.EndsWith("Tests", StringComparison.Ordinal) || last.EndsWith("Test", StringComparison.Ordinal)
            || content.Contains("<IsTestProject>true", StringComparison.OrdinalIgnoreCase)));
        var origin = IsSamplePath(path) ? "sample" : lang is not null && ManifestLangs.Contains(lang) ? "manifest" : IsGenerated(content) ? "generated" : "source";
        return [.. output.Where(d => d.Name.Length is > 0 and <= 300)
            .Select(d => d with { Scope = test ? "test" : d.Scope, Origin = d.Origin == "source" ? origin : d.Origin })
            // One row per name per file: the product's own if any is, at its first line.
            .GroupBy(d => (d.Role, d.Kind, d.Name, d.Form)).Select(g => g.MinBy(d => (d.Scope != "main", d.Line)))];
    }

    [ThreadStatic] static string? _linesOf;
    [ThreadStatic] static List<int>? _lineStarts;

    /// <summary>The line (from 1) of a place in the text: the line starts are found once per text.</summary>
    static long LineAt(string content, int index)
    {
        if (!ReferenceEquals(_linesOf, content) || _lineStarts is null)
        {
            _lineStarts = [0];
            for (var i = 0; i < content.Length; i++)
                if (content[i] == '\n') _lineStarts.Add(i + 1);
            _linesOf = content;
        }
        var at = _lineStarts.BinarySearch(index);
        return at >= 0 ? at + 1 : ~at;
    }

    static void Matches(Regex re, string content, string kind, List<Decl> output, bool lower, Func<Match, string>? join = null, string role = Uses,
        string form = "", Func<Match, string>? scope = null)
    {
        foreach (Match m in re.Matches(content))
        {
            var value = join is null ? m.Groups["name"].Value : join(m);
            if (value.Length == 0) continue;
            output.Add(new Decl(role, kind, lower ? value.ToLowerInvariant() : value, LineAt(content, m.Index), form, scope?.Invoke(m) ?? "main"));
        }
    }

    // --- .NET -------------------------------------------------------------------------

    static void MsBuild(string fileName, string content, List<Decl> output)
    {
        Matches(PackageReference(), content, "nuget", output, lower: true);
        // <ProjectReference Include="../../core/src/Core.csproj" />: the project it names, as a package of its name.
        foreach (Match m in ProjectReference().Matches(content))
        {
            var file = m.Groups["path"].Value.Replace('\\', '/');
            var stem = file[(file.LastIndexOf('/') + 1)..];
            if (stem.Contains('.')) stem = stem[..stem.LastIndexOf('.')];
            if (stem.Length > 0 && !stem.Contains('$')) output.Add(new Decl(Uses, "nuget", stem.ToLowerInvariant(), LineAt(content, m.Index)));
        }
        // <Using Include="Acme.Core" />: a global using, as a .cs file's.
        foreach (Match m in MsBuildUsing().Matches(content))
            output.Add(new Decl(Uses, m.Groups["static"].Success || m.Groups["alias"].Success ? "cs-type" : "cs", m.Groups["name"].Value, LineAt(content, m.Index), Form: "global"));
        if (!fileName.EndsWith("proj", StringComparison.OrdinalIgnoreCase)) return;
        // The package it makes: its PackageId, else its assembly's name, else the project file's ($(MSBuildProjectName) is it).
        var stemName = fileName[..fileName.LastIndexOf('.')];
        var id = PackageId().Match(content) is { Success: true } p ? p : AssemblyName().Match(content);
        var name = (id.Success ? id.Groups["name"].Value : stemName).Replace("$(MSBuildProjectName)", stemName, StringComparison.Ordinal)
            .Replace("$(AssemblyName)", AssemblyName().Match(content) is { Success: true } a ? a.Groups["name"].Value : stemName, StringComparison.Ordinal);
        if (!name.Contains("$(", StringComparison.Ordinal))
            output.Add(new Decl(Provides, "nuget", name.ToLowerInvariant(), id.Success ? LineAt(content, id.Index) : 1));
    }

    /// <summary>
    /// A C# file's namespaces, whole (a namespace inside another is Outer.Inner), and its usings: a namespace (cs, matched
    /// exactly), or a type or a namespace (cs-type: `using static`, an alias), matched as it is or one segment up.
    /// </summary>
    static void CSharp(string content, List<Decl> output)
    {
        var open = new Stack<(string Name, int Depth)>();
        var depth = 0;
        string? fileScoped = null;
        foreach (Match m in CsToken().Matches(content))
        {
            switch (m.Value)
            {
                case "{":
                    depth++;
                    break;
                case "}":
                    depth--;
                    while (open.Count > 0 && open.Peek().Depth > depth) open.Pop();
                    break;
                default:
                    var name = m.Groups["ns"].Value;
                    var outer = open.Count > 0 ? string.Join('.', open.Reverse().Select(o => o.Name)) + "." : fileScoped is null ? "" : fileScoped + ".";
                    output.Add(new Decl(Provides, "cs", outer + name, LineAt(content, m.Index)));
                    if (m.Groups["end"].Value == ";") fileScoped = name;
                    else
                    {
                        depth++;
                        open.Push((name, depth));
                    }
                    break;
            }
        }
        foreach (Match m in CsUsing().Matches(content))
            output.Add(new Decl(Uses, m.Groups["static"].Success || m.Groups["alias"].Success ? "cs-type" : "cs", m.Groups["name"].Value, LineAt(content, m.Index),
                Form: m.Groups["global"].Success ? "global" : ""));
    }

    // --- JavaScript and TypeScript ----------------------------------------------------

    static void PackageJson(string content, List<Decl> output)
    {
        using var doc = JsonDocument.Parse(content, new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true });
        var root = doc.RootElement;
        if (root.ValueKind != JsonValueKind.Object) return;
        if (root.TryGetProperty("name", out var n) && n.ValueKind == JsonValueKind.String && n.GetString() is { Length: > 0 } name)
            output.Add(new Decl(Provides, "npm", name.ToLowerInvariant(), Line(content, "\"name\"")));
        foreach (var section in new[] { "dependencies", "devDependencies", "peerDependencies", "optionalDependencies" })
        {
            if (!root.TryGetProperty(section, out var deps) || deps.ValueKind != JsonValueKind.Object) continue;
            foreach (var dep in deps.EnumerateObject())
                output.Add(new Decl(Uses, "npm", dep.Name.ToLowerInvariant(), Line(content, $"\"{dep.Name}\""), Scope: section == "devDependencies" ? "test" : "main"));
        }
    }

    /// <summary>A tsconfig's path aliases (compilerOptions.paths): imports of these are the repository's own code, not a package.</summary>
    static void TsConfig(string content, List<Decl> output)
    {
        using var doc = JsonDocument.Parse(content, new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true });
        if (doc.RootElement.ValueKind != JsonValueKind.Object || !doc.RootElement.TryGetProperty("compilerOptions", out var options)
            || options.ValueKind != JsonValueKind.Object || !options.TryGetProperty("paths", out var paths) || paths.ValueKind != JsonValueKind.Object) return;
        foreach (var alias in paths.EnumerateObject())
        {
            var name = alias.Name.EndsWith("/*", StringComparison.Ordinal) ? alias.Name[..^2] : alias.Name;
            if (name.Length > 0 && name != "*") output.Add(new Decl(Provides, "ts-alias", name.ToLowerInvariant(), Line(content, $"\"{alias.Name}\"")));
        }
    }

    static long Line(string content, string text) => content.IndexOf(text, StringComparison.Ordinal) is var i and >= 0 ? LineAt(content, i) : 1;

    static void JavaScript(string content, List<Decl> output)
    {
        foreach (Match m in JsImport().Matches(content))
        {
            var spec = m.Groups["spec"].Value;
            if (spec.StartsWith('.') || spec.StartsWith('/') || spec.Contains(':', StringComparison.Ordinal)) continue;
            // The package a bare specifier names: @scope/name, or its first part.
            var parts = spec.Split('/');
            var package = spec.StartsWith('@') && parts.Length > 1 ? parts[0] + "/" + parts[1] : parts[0];
            output.Add(new Decl(Uses, "npm", package.ToLowerInvariant(), LineAt(content, m.Index)));
        }
    }

    // --- Python -----------------------------------------------------------------------

    /// <summary>PEP 503: a distribution's name compares lower-case, runs of - _ . as one -.</summary>
    public static string PyName(string name) => PyNorm().Replace(name.Trim().ToLowerInvariant(), "-");

    static void PyProject(string content, List<Decl> output)
    {
        if (TomlName().Match(content) is { Success: true } n)
            output.Add(new Decl(Provides, "pypi", PyName(n.Groups["name"].Value), LineAt(content, n.Index)));
        // dependencies = ["a>=1", "b"] (PEP 621) and [tool.poetry.dependencies] a = "^1".
        if (TomlDependencies().Match(content) is { Success: true } list)
            foreach (Match d in QuotedRequirement().Matches(list.Groups["list"].Value))
                output.Add(new Decl(Uses, "pypi", PyName(d.Groups["name"].Value), LineAt(content, list.Index)));
        if (PoetryDependencies().Match(content) is { Success: true } poetry)
            foreach (Match d in TomlKey().Matches(poetry.Groups["body"].Value))
                if (d.Groups["name"].Value != "python")
                    output.Add(new Decl(Uses, "pypi", PyName(d.Groups["name"].Value), LineAt(content, poetry.Index)));
    }

    static void SetupCfg(string content, List<Decl> output)
    {
        if (IniName().Match(content) is { Success: true } n)
            output.Add(new Decl(Provides, "pypi", PyName(n.Groups["name"].Value), LineAt(content, n.Index)));
        if (IniInstallRequires().Match(content) is { Success: true } list)
            foreach (var line in list.Groups["body"].Value.Split('\n'))
                if (RequirementName().Match(line.Trim()) is { Success: true } d)
                    output.Add(new Decl(Uses, "pypi", PyName(d.Groups["name"].Value), LineAt(content, list.Index)));
    }

    /// <summary>requirements*.txt, constraints*.txt, and any .txt in a requirements/ folder (requirements/base.txt).</summary>
    static bool IsRequirements(string path, string name) =>
        name.StartsWith("requirements", StringComparison.OrdinalIgnoreCase) || name.StartsWith("constraints", StringComparison.OrdinalIgnoreCase)
        || path.Contains("requirements/", StringComparison.OrdinalIgnoreCase);

    static void Requirements(string content, List<Decl> output)
    {
        var lines = content.Split('\n');
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            // -e (editable) and --editable carry a URL or a path; other options are skipped.
            if (line.StartsWith("-e ", StringComparison.Ordinal) || line.StartsWith("--editable", StringComparison.Ordinal))
                line = line[(line.IndexOf(' ') + 1)..].Trim();
            // A URL's #egg= is not a comment.
            if (!line.Contains("://", StringComparison.Ordinal)) line = line.Split('#')[0].Trim();
            if (line.Length == 0 || line.StartsWith('-')) continue;
            // PEP 508: name @ url: the distribution, and the repository it comes from.
            if (Pep508Url().Match(line) is { Success: true } at)
            {
                output.Add(new Decl(Uses, "pypi", PyName(at.Groups["name"].Value), i + 1));
                line = at.Groups["url"].Value;
            }
            // git+https://gitlab.example.com/group/lib.git@v1#egg=lib: the repository itself.
            if (line.StartsWith("git+", StringComparison.Ordinal) || line.Contains("://", StringComparison.Ordinal))
            {
                // The revision after the path (@v1) and the fragment (#egg=) go; an @ in the host part (git@host) stays.
                var url = line.Replace("git+", "", StringComparison.Ordinal).Split('#')[0];
                var lastSlash = url.LastIndexOf('/');
                if (lastSlash >= 0 && url.IndexOf('@', lastSlash) is var rev and > 0) url = url[..rev];
                if (RepoPathOf(url) is { Length: > 0 } repo)
                    output.Add(new Decl(Uses, "repo", repo.ToLowerInvariant(), i + 1, "git"));
                continue;
            }
            if (RequirementName().Match(line) is { Success: true } m)
                output.Add(new Decl(Uses, "pypi", PyName(m.Groups["name"].Value), i + 1));
        }
    }

    [GeneratedRegex(@"^(?<name>[A-Za-z0-9][\w.-]*)(?:\[[^\]]*\])?\s*@\s*(?<url>\S+)")]
    private static partial Regex Pep508Url();

    static void Python(string path, string content, List<Decl> output)
    {
        // The module a file is: named from its import root, which only the repository's other files tell (the top of the
        // chain of package folders); resolved with them (Graph.PythonModules).
        if (path.EndsWith(".py", StringComparison.Ordinal))
            output.Add(new Decl(Provides, "py-file", path, 1));
        foreach (Match m in PyImport().Matches(content))
        {
            var module = m.Groups["from"].Success ? m.Groups["from"].Value : m.Groups["import"].Value;
            if (module.StartsWith('.')) continue;
            foreach (var one in module.Split(','))
                if (one.Trim().Split(' ')[0] is { Length: > 0 } dotted)
                    output.Add(new Decl(Uses, "py", dotted, LineAt(content, m.Index)));
        }
        if (SetupPyName().Match(content) is { Success: true } n && path.EndsWith("setup.py", StringComparison.Ordinal))
            output.Add(new Decl(Provides, "pypi", PyName(n.Groups["name"].Value), LineAt(content, n.Index)));
        if (path.EndsWith("setup.py", StringComparison.Ordinal) && SetupInstallRequires().Match(content) is { Success: true } list)
            foreach (Match d in QuotedRequirement().Matches(list.Groups["list"].Value))
                output.Add(new Decl(Uses, "pypi", PyName(d.Groups["name"].Value), LineAt(content, list.Index)));
    }

    // --- Go, Java, Rust, .proto ---------------------------------------------------------

    static void GoMod(string content, List<Decl> output)
    {
        if (GoModule().Match(content) is { Success: true } m)
            output.Add(new Decl(Provides, "go", m.Groups["name"].Value, LineAt(content, m.Index)));
        foreach (Match r in GoRequire().Matches(content))
        {
            // What the module needs only through another (// indirect) is not its own use.
            var line = content[r.Index..(content.IndexOf('\n', r.Index) is var nl and >= 0 ? nl : content.Length)];
            if (!line.Contains("// indirect", StringComparison.Ordinal))
                output.Add(new Decl(Uses, "go", r.Groups["name"].Value, LineAt(content, r.Index)));
        }
        // replace a => estate.example.com/team/a-fork v1: the fork is what it builds against.
        foreach (Match r in GoReplace().Matches(content))
            output.Add(new Decl(Uses, "go", r.Groups["to"].Value, LineAt(content, r.Index)));
    }

    /// <summary>A Go file's imports: in import ( … ) blocks and import lines only, with or without an alias (., _, a name).</summary>
    static void Go(string content, List<Decl> output)
    {
        foreach (Match block in GoImportBlock().Matches(content))
        {
            var body = block.Groups["body"];
            foreach (Match m in GoImportSpec().Matches(body.Value))
                output.Add(new Decl(Uses, "go", m.Groups["name"].Value, LineAt(content, body.Index + m.Index)));
        }
    }

    static void Pom(string content, List<Decl> output)
    {
        // The project's own coordinates: outside <parent>, <dependencies> and <build>.
        var own = PomSections().Replace(content, m => new string('\n', m.Value.Count(c => c == '\n')));
        var group = PomGroup().Match(own) is { Success: true } g ? g.Groups["v"].Value
            : PomParentGroup().Match(content) is { Success: true } pg ? pg.Groups["v"].Value : "";
        if (PomArtifact().Match(own) is { Success: true } a && group.Length > 0)
            output.Add(new Decl(Provides, "maven", $"{group}:{a.Groups["v"].Value}".ToLowerInvariant(), LineAt(content, a.Index)));
        // Its parent is a use too (corporate parents carry the build).
        if (PomParent().Match(content) is { Success: true } parent
            && PomGroup().Match(parent.Value) is { Success: true } pgroup && PomArtifact().Match(parent.Value) is { Success: true } part)
            output.Add(new Decl(Uses, "maven", $"{pgroup.Groups["v"].Value}:{part.Groups["v"].Value}".ToLowerInvariant(), LineAt(content, parent.Index)));
        // A <dependencyManagement> entry only pins a version, and build plugins are tools: neither is a use.
        var used = PomManaged().Replace(content, m => new string('\n', m.Value.Count(c => c == '\n')));
        foreach (Match d in PomDependencyBlock().Matches(used))
        {
            // groupId and artifactId in either order; ${project.groupId} is the project's own.
            if (PomGroup().Match(d.Value) is not { Success: true } dg || PomArtifact().Match(d.Value) is not { Success: true } da) continue;
            var depGroup = dg.Groups["v"].Value.Replace("${project.groupId}", group, StringComparison.Ordinal).Replace("${project.parent.groupId}", group, StringComparison.Ordinal);
            if (depGroup.Contains("${", StringComparison.Ordinal)) continue;
            var testScope = d.Value.Contains("<scope>test</scope>", StringComparison.Ordinal);
            output.Add(new Decl(Uses, "maven", $"{depGroup}:{da.Groups["v"].Value}".ToLowerInvariant(), LineAt(content, d.Index), Scope: testScope ? "test" : "main"));
        }
    }

    /// <summary>A Gradle version catalog's libraries: what the build's libs.x references name.</summary>
    static void GradleCatalog(string content, List<Decl> output)
    {
        var libraries = TomlSection().Match(content);
        if (!libraries.Success) return;
        foreach (Match m in CatalogEntry().Matches(libraries.Groups["body"].Value))
            output.Add(new Decl(Uses, "maven", $"{m.Groups["g"].Value}:{m.Groups["a"].Value}".ToLowerInvariant(), LineAt(content, libraries.Groups["body"].Index + m.Index)));
    }

    [GeneratedRegex(@"^\[libraries\]\s*\n(?<body>(?:(?!\[).*\n?)*)", RegexOptions.Multiline)]
    private static partial Regex TomlSection();

    static void Java(string content, List<Decl> output)
    {
        if (JavaPackage().Match(content) is { Success: true } p)
            output.Add(new Decl(Provides, "java", p.Groups["name"].Value, LineAt(content, p.Index)));
        foreach (Match m in JavaImport().Matches(content))
        {
            // import a.b.*: the package a.b (the greedy name takes the dot before the star).
            var name = m.Groups["name"].Value;
            output.Add(new Decl(Uses, name.EndsWith('.') ? "java-package" : "java", name.TrimEnd('.'), LineAt(content, m.Index)));
        }
    }

    static void Cargo(string content, List<Decl> output)
    {
        if (CargoPackage().Match(content) is { Success: true } p && TomlName().Match(p.Groups["body"].Value) is { Success: true } n)
            output.Add(new Decl(Provides, "cargo", n.Groups["name"].Value.ToLowerInvariant().Replace('_', '-'), LineAt(content, p.Index)));
        foreach (Match section in CargoDependencies().Matches(content))
        {
            var dev = section.Value.StartsWith("[dev-", StringComparison.Ordinal) || section.Value.Contains(".dev-dependencies]", StringComparison.Ordinal);
            foreach (var line in section.Groups["body"].Value.Split('\n'))
                if (TomlKey().Match(line) is { Success: true } d)
                {
                    // codec = { package = "acme-codec" }: the package is acme-codec, whatever the code calls it.
                    var name = CargoRename().Match(line) is { Success: true } r ? r.Groups["name"].Value : d.Groups["name"].Value;
                    output.Add(new Decl(Uses, "cargo", name.ToLowerInvariant().Replace('_', '-'), LineAt(content, section.Index), Scope: dev ? "test" : "main"));
                }
        }
    }

    static void Proto(string path, string content, List<Decl> output)
    {
        output.Add(new Decl(Provides, "proto", path, 1));
        foreach (Match m in ProtoImport().Matches(content))
            output.Add(new Decl(Uses, "proto", m.Groups["name"].Value, LineAt(content, m.Index)));
    }

    // --- Repositories by path: submodules, CI, images ------------------------------------

    static void Yaml(string fileName, string content, List<Decl> output, bool isCi = false)
    {
        isCi = isCi || fileName.EndsWith("gitlab-ci.yml", StringComparison.OrdinalIgnoreCase) || fileName.EndsWith("gitlab-ci.yaml", StringComparison.OrdinalIgnoreCase);
        if (isCi)
        {
            Matches(CiProject(), content, "repo", output, lower: true, join: m => m.Groups["name"].Value.Trim('\'', '"', '/'), form: "ci");
            // A CI/CD component: host/group/project/component@version is its project's.
            Matches(CiComponent(), content, "repo", output, lower: true, join: m => m.Groups["project"].Value, form: "ci");
        }
        // compose files, Kubernetes manifests, Helm values: image: group/name:tag and repository: group/name. A chart's
        // repository: is where its dependencies' charts come from, not an image.
        if (fileName is "Chart.yaml" or "Chart.lock" or "requirements.yaml") return;
        Matches(YamlImage(), content, "image", output, lower: true, join: m => ImagePath(m.Groups["image"].Value), form: isCi ? "ci" : "deploy");
    }

    /// <summary>group/sub/name from a git URL (https://host/group/name.git, git@host:group/name.git); empty when it is not one.</summary>
    public static string RepoPathOf(string url)
    {
        var u = url.Trim().Trim('"', '\'');
        if (u.EndsWith(".git", StringComparison.OrdinalIgnoreCase)) u = u[..^4];
        if (u.StartsWith("git@", StringComparison.Ordinal) && u.IndexOf(':') is var colon and > 0) return u[(colon + 1)..].Trim('/');
        var scheme = u.IndexOf("://", StringComparison.Ordinal);
        if (scheme < 0) return "";
        var rest = u[(scheme + 3)..];
        var slash = rest.IndexOf('/');
        return slash < 0 ? "" : rest[(slash + 1)..].Trim('/');
    }

    /// <summary>An image's path in its registry, without the registry's host or the tag (registry.example.com:5000/group/app:1.2 is group/app).</summary>
    public static string ImagePath(string image)
    {
        var i = image.Trim().Trim('"', '\'');
        if (i.Contains('$', StringComparison.Ordinal)) return "";
        var at = i.IndexOf('@');
        if (at >= 0) i = i[..at];
        var parts = i.Split('/').ToList();
        // A first part with a dot or a port, or "localhost", is a registry's host.
        if (parts.Count > 1 && (parts[0].Contains('.') || parts[0].Contains(':') || parts[0] == "localhost")) parts.RemoveAt(0);
        var last = parts[^1];
        var colon = last.LastIndexOf(':');
        if (colon > 0) parts[^1] = last[..colon];
        // One part is a public image's name (nginx, python): never this estate's; but in a private registry (ECR, ACR,
        // Artifact Registry) a flat name is a repository's own, matched by the repository's name (*/name).
        if (parts.Count == 1 && i.Split('/')[0] is var host && PrivateRegistry().IsMatch(host)) return "*/" + parts[0];
        return parts.Count >= 2 ? string.Join('/', parts) : "";
    }

    // --- Patterns -----------------------------------------------------------------------

    [GeneratedRegex(@"<PackageReference\b[^>]*?\sInclude\s*=\s*""(?<name>[^""$]+)""", RegexOptions.IgnoreCase)]
    private static partial Regex PackageReference();
    [GeneratedRegex(@"<ProjectReference\b[^>]*?\sInclude\s*=\s*""(?<path>[^""]+)""", RegexOptions.IgnoreCase)]
    private static partial Regex ProjectReference();
    [GeneratedRegex(@"<Using\b(?=[^>]*\sInclude\s*=\s*""(?<name>[A-Za-z_][\w.]*)"")(?:(?=[^>]*\s(?<static>Static)\s*=\s*""true"")|(?=[^>]*\s(?<alias>Alias)\s*=))?", RegexOptions.IgnoreCase)]
    private static partial Regex MsBuildUsing();
    [GeneratedRegex("""<PackageId>\s*(?<name>[^<\s]+)\s*</PackageId>""", RegexOptions.IgnoreCase)]
    private static partial Regex PackageId();
    [GeneratedRegex("""<AssemblyName>\s*(?<name>[^<\s]+)\s*</AssemblyName>""", RegexOptions.IgnoreCase)]
    private static partial Regex AssemblyName();
    [GeneratedRegex(@"<package\s+id\s*=\s*""(?<name>[^""]+)""", RegexOptions.IgnoreCase)]
    private static partial Regex PackagesConfig();
    /// <summary>A namespace's start (its name, and { or ; after it), or a brace: what nests one namespace in another.</summary>
    [GeneratedRegex(@"\bnamespace\s+(?<ns>[A-Za-z_][\w.]*)\s*(?<end>[{;])|[{}]")]
    private static partial Regex CsToken();
    [GeneratedRegex(@"^\s*(?<global>global\s+)?using\s+(?:(?<static>static)\s+)?(?:(?<alias>\w+)\s*=\s*)?(?:global::)?(?<name>[A-Za-z_][\w.]*)\s*;", RegexOptions.Multiline)]
    private static partial Regex CsUsing();
    [GeneratedRegex("""(?:\bimport\s+(?:[\w*{}\s,]+\s+from\s+)?|\bexport\s+[\w*{}\s,]+\s+from\s+|\brequire\s*\(\s*|\bimport\s*\(\s*)['"](?<spec>[^'"\s]+)['"]""")]
    private static partial Regex JsImport();
    [GeneratedRegex(@"[-_.]+")]
    private static partial Regex PyNorm();
    [GeneratedRegex(@"^\s*name\s*=\s*['""](?<name>[^'""]+)['""]", RegexOptions.Multiline)]
    private static partial Regex TomlName();
    /// <summary>dependencies = [ … ]: quoted items (a ] inside one, as in extras, does not end the list).</summary>
    [GeneratedRegex(@"^\s*dependencies\s*=\s*\[(?<list>(?:""[^""]*""|'[^']*'|[^\]""'])*)\]", RegexOptions.Multiline)]
    private static partial Regex TomlDependencies();
    [GeneratedRegex(@"^\[tool\.poetry\.dependencies\]\s*\n(?<body>(?:(?!\[).*\n?)*)", RegexOptions.Multiline)]
    private static partial Regex PoetryDependencies();
    [GeneratedRegex(@"^\s*(?<name>[A-Za-z0-9][\w.-]*)\s*=", RegexOptions.Multiline)]
    private static partial Regex TomlKey();
    [GeneratedRegex("""['"](?<name>[A-Za-z0-9][\w.-]*)""")]
    private static partial Regex QuotedRequirement();
    [GeneratedRegex(@"^(?<name>[A-Za-z0-9][\w.-]*)")]
    private static partial Regex RequirementName();
    [GeneratedRegex(@"^\s*name\s*=\s*(?<name>\S+)", RegexOptions.Multiline)]
    private static partial Regex IniName();
    [GeneratedRegex(@"^\s*install_requires\s*=\s*\n(?<body>(?:[ \t]+\S.*\n?)*)", RegexOptions.Multiline)]
    private static partial Regex IniInstallRequires();
    [GeneratedRegex(@"^[ \t]*(?:from\s+(?<from>[\w.]+)\s+import|import\s+(?<import>[\w.]+(?:\s+as\s+\w+)?(?:\s*,\s*[\w.]+(?:\s+as\s+\w+)?)*))", RegexOptions.Multiline)]
    private static partial Regex PyImport();
    [GeneratedRegex("""\bname\s*=\s*['"](?<name>[^'"]+)['"]""")]
    private static partial Regex SetupPyName();
    [GeneratedRegex(@"\binstall_requires\s*=\s*\[(?<list>(?:""[^""]*""|'[^']*'|[^\]""'])*)\]")]
    private static partial Regex SetupInstallRequires();
    [GeneratedRegex(@"^module\s+(?<name>\S+)", RegexOptions.Multiline)]
    private static partial Regex GoModule();
    [GeneratedRegex(@"^\s*(?:require\s+)?(?<name>[a-z0-9][\w.\-]*\.[a-z]{2,}/[\w./\-]+)\s+v\d", RegexOptions.Multiline)]
    private static partial Regex GoRequire();
    /// <summary>import "x" (a line), or import ( … ): the specs.</summary>
    [GeneratedRegex(@"^\s*import\s*(?:\((?<body>[^)]*)\)|(?<body>(?:[\w.]+\s+)?""[^""\n]*""))", RegexOptions.Multiline)]
    private static partial Regex GoImportBlock();
    [GeneratedRegex(@"(?:^|\n)\s*(?:[\w.]+\s+)?""(?<name>[a-z0-9][\w.\-]*\.[a-z]{2,}/[\w./\-]+)""")]
    private static partial Regex GoImportSpec();
    [GeneratedRegex(@"^\s*(?:replace\s+)?[^\s=]+(?:\s+v\S+)?\s*=>\s*(?<to>[a-z0-9][\w.\-]*\.[a-z]{2,}/[\w./\-]+)\s+v\d", RegexOptions.Multiline)]
    private static partial Regex GoReplace();
    [GeneratedRegex(@"<(?<tag>parent|dependencies|dependencyManagement|build|profiles|plugins)>[\s\S]*?</\k<tag>>")]
    private static partial Regex PomSections();
    [GeneratedRegex(@"<dependency>[\s\S]*?</dependency>")]
    private static partial Regex PomDependencyBlock();
    [GeneratedRegex(@"<parent>[\s\S]*?</parent>")]
    private static partial Regex PomParent();
    [GeneratedRegex(@"<(?<tag>dependencyManagement|build|plugins)>[\s\S]*?</\k<tag>>")]
    private static partial Regex PomManaged();
    [GeneratedRegex(@"<groupId>\s*(?<v>[^<\s]+)\s*</groupId>")]
    private static partial Regex PomGroup();
    [GeneratedRegex(@"<parent>[\s\S]*?<groupId>\s*(?<v>[^<\s]+)\s*</groupId>")]
    private static partial Regex PomParentGroup();
    [GeneratedRegex(@"<artifactId>\s*(?<v>[^<\s]+)\s*</artifactId>")]
    private static partial Regex PomArtifact();
    [GeneratedRegex(@"<dependency>\s*(?:<!--[\s\S]*?-->\s*)*<groupId>\s*(?<g>[^<\s]+)\s*</groupId>\s*<artifactId>\s*(?<a>[^<\s]+)\s*</artifactId>")]
    private static partial Regex PomDependency();
    [GeneratedRegex("""\b(?<conf>implementation|api|compile|compileOnly|runtimeOnly|testImplementation|testRuntimeOnly|testCompileOnly|annotationProcessor|kapt|ksp|classpath)\s*\(?\s*(?:(?:enforcedPlatform|platform)\s*\(\s*)?['"](?<g>[\w.\-]+):(?<a>[\w.\-]+)(?::[^'"]*)?['"]""")]
    private static partial Regex GradleDep();
    [GeneratedRegex("""(?:\b(?<conf>\w+)\s*\(?\s*)?\bgroup\s*:\s*['"](?<g>[\w.\-]+)['"]\s*,\s*name\s*:\s*['"](?<a>[\w.\-]+)['"]""")]
    private static partial Regex GradleMapDep();
    [GeneratedRegex("""(?:module\s*=\s*|^\s*[\w.\-]+\s*=\s*)['"](?<g>[\w.\-]+):(?<a>[\w.\-]+)(?::[^'"]*)?['"]""", RegexOptions.Multiline)]
    private static partial Regex CatalogEntry();
    [GeneratedRegex(@"^\s*package\s+(?<name>[a-z_][\w.]*)\s*;?", RegexOptions.Multiline)]
    private static partial Regex JavaPackage();
    [GeneratedRegex(@"^\s*import\s+(?:static\s+)?(?<name>[a-z_][\w.]*)(?:\.\*)?\s*;?", RegexOptions.Multiline)]
    private static partial Regex JavaImport();
    [GeneratedRegex(@"^\[package\]\s*\n(?<body>(?:(?!\[).*\n?)*)", RegexOptions.Multiline)]
    private static partial Regex CargoPackage();
    [GeneratedRegex(@"^\[(?:workspace\.|target\.[^\]]+\.)?(?:dev-|build-)?dependencies\]\s*\n(?<body>(?:(?!\[).*\n?)*)", RegexOptions.Multiline)]
    private static partial Regex CargoDependencies();
    [GeneratedRegex(@"\bpackage\s*=\s*""(?<name>[^""]+)""")]
    private static partial Regex CargoRename();
    [GeneratedRegex(@"^\s*(?:pub\s+)?(?:use|extern\s+crate)\s+(?<crate>[a-z_][a-z0-9_]*)", RegexOptions.Multiline)]
    private static partial Regex RustUse();
    [GeneratedRegex(@"^\s*import\s+(?:public\s+|weak\s+)?""(?<name>[^""]+\.proto)""", RegexOptions.Multiline)]
    private static partial Regex ProtoImport();
    [GeneratedRegex(@"^\s*url\s*=\s*(?<url>\S+)", RegexOptions.Multiline)]
    private static partial Regex SubmoduleUrl();
    [GeneratedRegex(@"^\s*-?\s*project\s*:\s*(?<name>['""]?[\w.\-/]+['""]?)\s*$", RegexOptions.Multiline)]
    private static partial Regex CiProject();
    [GeneratedRegex(@"^\s*-?\s*component\s*:\s*['""]?[\w.\-]+\.[a-z]{2,}(?::\d+)?/(?<project>[\w.\-/]+)/[\w.\-]+@[\w.\-$]+['""]?\s*$", RegexOptions.Multiline)]
    private static partial Regex CiComponent();
    /// <summary>image: x, repository: x, and the extended forms (image:\n  name: x; kustomize's newName: x).</summary>
    [GeneratedRegex(@"^\s*-?\s*(?:image|repository|newName)\s*:\s*['""]?(?<image>[\w.\-/:@${}]+)['""]?\s*$|^\s*image\s*:\s*\n\s+name\s*:\s*['""]?(?<image>[\w.\-/:@${}]+)['""]?\s*$", RegexOptions.Multiline)]
    private static partial Regex YamlImage();
    [GeneratedRegex(@"\.dkr\.ecr\.|\.azurecr\.io$|-docker\.pkg\.dev$|^gcr\.io$|\.gcr\.io$", RegexOptions.IgnoreCase)]
    private static partial Regex PrivateRegistry();
    [GeneratedRegex(@"^\s*FROM\s+(?:--platform=\S+\s+)?(?<image>\S+)", RegexOptions.Multiline | RegexOptions.IgnoreCase)]
    private static partial Regex DockerFrom();
}
